# -------------------------------------------------------------------------------------
# Copyright 2020 Telefónica Soluciones de Informática y Comunicaciones de España, S.A.U.
# This file is part of Pentaho DSP.
# Pentaho DSP is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# Pentaho DSP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
# General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this software. If not, see http://www.gnu.org/licenses/.
# For those usages not covered by this license please contact with
# sc_support at telefonica dot com
# -------------------------------------------------------------------------------------

name: Maven Build

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Standard steps - check out repo & build with maven
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Initialize Maven
      run: mvn -B initialize
    - name: Build with Maven
      run: mvn -B package

    # Create a release for the current tag
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    # Get tag name.
    - name: Get Version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    # Upload compiled jar to the release
    - name: Upload Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/pentaho-dsp-${{ steps.get_version.outputs.VERSION }}.jar
        asset_name: pentaho-dsp-${{ steps.get_version.outputs.VERSION }}.jar
        asset_content_type: application/java-archive

